# fly.toml file generated for discord-rs on 2023-03-10T09:09:33+08:00

app = "discord-rs"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"
processes = []

[env]

[experimental]
  auto_rollback = true
  cmd = "./discord-rs"
